export const currencies=[
    {
      name:"USD",
      symbol:"$",
      convertionRate:1
    },
    {
      name:"Pound",
      symbol:"£",
      convertionRate:2
    },
    {
      name:"Euro",
      symbol:"€",
      convertionRate:1.01
    },
    {
      name:"Yen",
      symbol:"¥",
      convertionRate:3
    },
  ]